---
- name: Configure Web Servers
  hosts: web
  become: true
  tasks:
    - name: Install HTTPD
      yum:
        name: httpd
        state: present

    - name: Start and Enable HTTPD
      service:
        name: httpd
        state: started
        enabled: true

    - name: Copy trillo website to the servers
      copy:
        src: ~/trillo/
        dest: /var/www/html/trillo/
        
